// <auto-generated />
using System;
using Ef_platzy.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Ef_platzy.Migrations
{
    [DbContext(typeof(Ef_PlatzyContex))]
    [Migration("20220615041726_SeedData")]
    partial class SeedData
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Ef_platzy.Models.Category", b =>
                {
                    b.Property<Guid>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Effort")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CategoryId");

                    b.ToTable("Category", (string)null);

                    b.HasData(
                        new
                        {
                            CategoryId = new Guid("d25eb6c9-b078-4771-a1a1-ccc9a7cd0755"),
                            Effort = 20,
                            Name = "Pending Activities"
                        },
                        new
                        {
                            CategoryId = new Guid("62dd1227-8d77-4ed6-b811-ddc4530c97ae"),
                            Effort = 50,
                            Name = "Personal Activities"
                        });
                });

            modelBuilder.Entity("Ef_platzy.Models.Task", b =>
                {
                    b.Property<Guid>("TaskId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CategoryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("DateCreated")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("priority")
                        .HasColumnType("int");

                    b.HasKey("TaskId");

                    b.HasIndex("CategoryId");

                    b.ToTable("Task", (string)null);

                    b.HasData(
                        new
                        {
                            TaskId = new Guid("03ebb742-cbb2-46b4-a8a8-957f4ae873bd"),
                            CategoryId = new Guid("d25eb6c9-b078-4771-a1a1-ccc9a7cd0755"),
                            DateCreated = new DateTime(2022, 6, 14, 23, 17, 26, 4, DateTimeKind.Local).AddTicks(8085),
                            Title = "Public Services pay",
                            priority = 1
                        },
                        new
                        {
                            TaskId = new Guid("57b67926-b7fe-4a04-84d7-ec800dfdf7a5"),
                            CategoryId = new Guid("d25eb6c9-b078-4771-a1a1-ccc9a7cd0755"),
                            DateCreated = new DateTime(2022, 6, 14, 23, 17, 26, 4, DateTimeKind.Local).AddTicks(8121),
                            Title = "pay the house cleaning",
                            priority = 2
                        },
                        new
                        {
                            TaskId = new Guid("b3a7249f-5d58-4ae6-aa6b-43dd7c3d7807"),
                            CategoryId = new Guid("62dd1227-8d77-4ed6-b811-ddc4530c97ae"),
                            DateCreated = new DateTime(2022, 6, 14, 23, 17, 26, 4, DateTimeKind.Local).AddTicks(8125),
                            Title = "Call mom",
                            priority = 0
                        });
                });

            modelBuilder.Entity("Ef_platzy.Models.Task", b =>
                {
                    b.HasOne("Ef_platzy.Models.Category", "Category")
                        .WithMany("Task")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("Ef_platzy.Models.Category", b =>
                {
                    b.Navigation("Task");
                });
#pragma warning restore 612, 618
        }
    }
}
